title: Jekyll Tiddlers
description: a non-linear personal web notebook with Jekyll

defaults:
  - values:
      layout: null
  - scope:
      type: tiddlers
    values:
      layout: tiddly


collections:
  tiddlers:
    output: true
    permalink: /tiddlers/:path.json
    exclude_fields: [ layout, output, content, path, relative_path, url, collection ]

exclude: [ jekyll-tiddlers ]
